task:
  title: Is this a cat?
dataset:
  directory: /Users/chris_zhu/Documents/Github/labelling-tool/dataset/cat_or_dog
  data_type: images
  judgements_file: /Users/chris_zhu/Documents/Github/labelling-tool/outputs/cat_or_dog/labels.csv
label:
  type: binary
model_directory: /Users/chris_zhu/Documents/Github/labelling-tool/outputs/cat_or_dog/models/
user: chris
