task:
  title: Is this a cat?
dataset:
  directory: dataset/cat_or_dog
  data_type: images
  judgements_file: outputs/cat_or_dog/labels.csv
label:
  type: binary
model_directory: outputs/cat_or_dog/models/
user: chris
