task:
  title: NER Tags for query
dataset:
  directory: dataset/ner_sequence
  data_type: text
  judgements_file: outputs/ner_sequence/labels.csv
label:
  type: sequence
  length_equality: true
  valid_tokens:
    - O
    - B-LOC
    - I-LOC
    - B-VERT
    - I-VERT
    - B-TIME
    - I-TIME
    - B-PRICE
    - I-PRICE
    - B-REF
    - I-REF
    - B-ATTR
    - I-ATTR
    - B-OCC
    - I-OCC
model_directory: outputs/ner_sequence/models/
user: chris
model_labelling: false
