task:
  title: Noun Chunking Tag for this query
dataset:
  directory: /Users/chris_zhu/Documents/Github/labelling-tool/dataset/airbnb_queries
  data_type: text
  judgements_file: /Users/chris_zhu/Documents/Github/labelling-tool/outputs/np_chunking/labels.csv
label:
  type: sequence
  length_equality: true
  valid_tokens:
    - B-NP
    - I-NP
    - O
model_directory: /Users/chris_zhu/Documents/Github/labelling-tool/outputs/np_chunking/models/
user: chris
model_labelling: false
