task:
  title: SEO Logs
dataset:
  directory: /Users/chris_zhu/Documents/Github/labelling-tool/dataset/all_seo_logs/seo_logs_0
  data_type: text
  judgements_file: /Users/chris_zhu/Documents/Github/labelling-tool/outputs/seo_logs/labels.csv
label:
  type: sequence
  length_equality: true
  valid_tokens:
    - O
    - B-LOC
    - I-LOC
    - B-CON
    - I-CON
    - B-TIME
    - I-TIME
    - B-PRICE
    - I-PRICE
    - B-OCC
    - I-OCC
model:
  custom: true
  module: sequence_tagging.sequence_tagger_wrapper.SequenceTaggerWrapper
  directory: /Users/chris_zhu/Documents/Github/labelling-tool/vendor/model
model_directory: /Users/chris_zhu/Documents/Github/labelling-tool/outputs/seo_logs/models/
user: chris
