task:
  title: Label this sequence with its NERs
dataset:
  directory: dataset/sequence_labelling/
  data_type: json
  judgements_file: outputs/sequence_labelling/labels.csv
label:
  type: sequence
  default_class: O
  classes:
    - B-ADJP
    - I-ADJP
    - B-ADVP
    - I-ADVP
    - B-CONJP
    - I-CONJP
    - B-INTJ
    - I-INTJ
    - B-LST
    - I-LST
    - B-NP
    - I-NP
    - B-PP
    - I-PP
    - B-PRT
    - I-PRT
    - B-SBAR
    - I-SBAR
    - B-UCP
    - I-UCP
    - B-VP
    - I-VP
model:
  directory: outputs/sequence_labelling/models/
  pretrain_file: dataset/pretrain.csv
user: chris
